filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /src/logs/src/logs/*.log
    json:
      keys_under_root: true
      overwrite_keys: true
      add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

setup.template.enabled: true
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

logging.level: info
