services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    labels:
      - "log_type=node-backend"
    networks:
      - mynetwork
    volumes:
        - ./nodejs-logs:/src/logs

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - mynetwork


networks:
  mynetwork:
    driver: bridge

