services:
  backend:
    build: ./backend
    restart: on-failure  # Restartuj kontener tylko w przypadku błędu
    ports:
      - "127.0.0.1:5050:5050"
    networks:
      - net
    volumes:
      - /var/myapp/logs:/tmp/myapp
      - /log/url-shortener:/log/url-shortener

  frontend:
    build: ./frontend
    restart: on-failure
    ports:
      - "127.0.0.1:3050:80"
    networks:
      - net

networks:
  net:
    driver: bridge
