version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  documentation:
    image: nginx:latest
    container_name: documentation
    volumes:
      - ./documentation:/usr/share/nginx/html:ro
    ports:
      - "8080:80"


networks:
  mynetwork:
    driver: bridge

